### ISSUE TITLE
[table] Loading .wav files with more than the selected sample/cycle option * 256 maximum cycles causes crash

### ISSUE THREAD

**Issue by espenstoro** [IggyLabs/IggyLabsModules#21]
Hi. Trying to load a bunch of Serum wavetavles (which don't get scanned properly in Nysthi Seven Seas for some reason, although the size allegedly is the same), but it crashes Rack every time. Any other size works, but it'll just sound like glitching and stuttering, obviously. With that in mind, an additional question would be if these kind of wavetables are intended to work in Table? That would be really nice, because many of us have incredible amounts of those, and they're distributed everywhere. :)
Rack 1.1.6, plugin version 1.0.1, Windows.

**Comment by isabelgk** [comment]
Hi, Serum wavetables are 2048 samples/cycle. Are you using the 2048 import option? This option doesn't refer to the number of frames/cycles in the wavetable, rather the length of the single cycle.

I'm facing no issues loading the stock Serum wavetables using the 2048 samples/cycle option and cannot reproduce.

**Comment by isabelgk** [comment]
However, I can reproduce crashes when using a smaller import cycle size than the wavetable intends. For example, a wavetable of 2048 samples/cycle with 256 cycles will crash when using the 256 samples/cycle option. This is because the total number of samples is too large for `x samples/cycle * 256 cycles` now that `x` is too small. The check on it is failing for some reason I'll fix. 

However, you shouldn't be facing any issues importing standard Serum wavetables with the proper 2048 samples/cycle option.

**Comment by isabelgk** [comment]
If you are still having issues with importing Serum wavetables using the 2048 sample/cycle option, please let me know, and I'll reopen the issue, but I believe the crashing is due to the issue I mentioned. That bug will be fixed when I go to the next release.

**Comment by espenstoro** [comment]
Ok, thanks. It gets confusing when different software uses different terminology. The instinct was to go for 256, since Serum uses 256 units of something or other.
Anyway, it does indeed work. :)

**Comment by isabelgk** [comment]
No worries, I agree it's confusing! I'm working on some ways to make it more obvious which way to import! Thanks for helping me find the other bug, too :)
